cpp: main.cpp
	g++ -o main main.cpp -std=c++23 -O3
	./main

dark: main.cpp
	g++ -o main main.cpp -std=c++23 -O3 -DTREE
	./main

darktest: main.cpp
	g++ -o main main.cpp -std=c++23 -O3 -DTREE -DTEST
	./main